In [1]:
from fastai.vision import *

In [20]:
def stats(x):
    print(f'mean:{x.mean():.2f}, std:{x.std():.2f}, var:{x.var():.2f}')

In [21]:
x = torch.randn(1000, 784)
w = torch.randn((784, 64))

In [22]:
res = x@w
stats(res)

mean:-0.02, std:27.97, var:782.49


In [5]:
v = torch.randn(1000)
(v - v.mean()).mean()

tensor(-6.0201e-09)

In [6]:
(v - v.mean()).pow(2).mean(), v.var()

(tensor(0.9430), tensor(0.9439))

In [7]:
(v/10).var()

tensor(0.0094)

In [8]:
(v/math.sqrt(10)).var()

tensor(0.0944)

In [9]:
w1 = w/math.sqrt(784)
res = x@w1
stats(res)

mean:-0.00, std:1.01, var:1.01


In [28]:
ws = [w1]+[torch.randn((64,64))/math.sqrt(64) for _ in range(50)]
res = x
for w_ in ws: res = res@w_
stats(res)

mean:-0.00, std:1.39, var:1.93


In [11]:
def relu(x): return x.clamp_min(0.)

In [30]:
relu(torch.tensor([1, 2, -1, -3, 0, 4]))

tensor([1, 2, 0, 0, 0, 4])

In [12]:
x.shape

torch.Size([1000, 784])

In [13]:
ws[0].shape

torch.Size([784, 64])

In [14]:
w1.var()

tensor(0.0013)

In [37]:
w2 = w*math.sqrt(2/784)
stats(relu(x@w2))

In [38]:
stats(relu(x@w2))

mean:0.56, std:0.82, var:0.68


In [59]:
def get_weight(*size): return torch.randn(*size)*math.sqrt(1/size[0])

In [45]:
# Test it, is it doing the same as before?
w = get_weight(784, 64)
stats(x@w)

mean:-0.00, std:1.00, var:0.99


In [46]:
w = get_weight(784, 64)
stats(relu(x@w))

mean:0.39, std:0.58, var:0.34


In [49]:
def forward_one(x, w): return relu(x@w)
def forward_all(x, ws):
    for w in ws: x = forward_one(x, w)
    return x

In [55]:
def get_ws(n_in, get_ws_func):
    w1 = get_ws_func(n_in, 64)
    ws = [get_ws_func(64,64) for _ in range(50)]
    return [w1] + ws

In [57]:
ws = get_ws(784, get_weight)
res = forward_all(x, ws)
stats(res)

mean:0.00, std:0.00, var:0.00


In [62]:
def get_weight_relu(*size):
    return torch.randn(*size)*math.sqrt(2/size[0])

In [67]:
ws = get_ws(784, get_weight_relu)
res = forward_all(x, ws)
stats(res)

mean:0.65, std:0.97, var:0.94


In [40]:
ws = [w*math.sqrt(2/784)]+[torch.randn((64,64))*math.sqrt(2/64) for _ in range(50)]
res = x
for w_ in ws: res = relu(res@w_)
stats(res)

mean:0.75, std:1.15, var:1.32


In [29]:
x = torch.randn(5); stats(x)
x

mean:0.07, std:1.08, var:1.16


tensor([ 0.0870, -1.3116, -0.5717,  1.4826,  0.6410])

In [31]:
x = sum([torch.randn(5) for _ in range(100)]); stats(x)
x

mean:2.84, std:7.48, var:55.91


tensor([-3.7550, 12.8912,  2.4218,  7.4103, -4.7788])

In [51]:
sum([torch.randn(1) for _ in range(100)])

tensor([23.3228])